# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
      
      
      
      
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
          
          - name: Netlify Actions
  # You may pin to the exact commit or the version.
  # uses: nwtgck/actions-netlify@db90f8c196ec8808d9765741da1be62c48db8867
  uses: nwtgck/actions-netlify@v1.1.11
  with:
    # Publish directory
    publish-dir: master
    # Functions directory
    functions-dir: # optional
    # Custom deploy message for Netlify
    deploy-message: # optional
    # GitHub token
    github-token: # optional
    # Production branch
    production-branch: # optional
    # Indicate wether to deploy production build
    production-deploy: # optional
    # Enable pull request comment
    enable-pull-request-comment: # optional
    # Enable commit comment
    enable-commit-comment: # optional
    # Enable GitHub commit status
    enable-commit-status: # optional
    # Overwrites pull request comment
    overwrites-pull-request-comment: # optional
    # Path to netlify.toml
    netlify-config-path: # optional
    # Specifies the prefix for the deployment URL
    alias: # optional
    # Environment name of GitHub Deployments
    github-deployment-environment: # optional
